#!/usr/bin/bash
":" //# comment; exec /usr/bin/env node --input-type=module - "$@" < "$0"

import {getRando} from "dbmage"
;(async() => {
	const rando = await getRando()
	const howMany = parseInt(process.argv[2] ?? 1)
	for (let i = 0; i < howMany; i++)
		console.log(rando.randomId().toString())
})()
